#!/usr/bin/env bash
# 95-private.sh — optional private overlay. Does nothing unless you create
# tools.d/private.git, which is gitignored and ships with no default.
#
# This is the escape hatch for repos that can't be public: put one clone URL
# per line in tools.d/private.git and this module registers your SSH key with
# GitHub and clones them alongside the public toolkit. With no manifest it is
# a clean no-op, which is what a stranger running bootstrap.sh gets.
[ -n "${W1LD0S_ROOT:-}" ] || { W1LD0S_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; source "$W1LD0S_ROOT/lib/common.sh"; }

PRIVATE_MANIFEST="$W1LD0S_ROOT/tools.d/private.git"

if [ ! -f "$PRIVATE_MANIFEST" ]; then
  log "No private overlay configured (tools.d/private.git absent) — nothing to do."
  return 0 2>/dev/null || exit 0
fi

mapfile -t PRIVATE_REPOS < <(read_list private.git)
if [ "${#PRIVATE_REPOS[@]}" -eq 0 ]; then
  log "tools.d/private.git has no entries — nothing to do."
  return 0 2>/dev/null || exit 0
fi

SSH_KEY="$HOME/.ssh/id_ed25519"   # generated by module 90
if [ ! -f "$SSH_KEY.pub" ]; then
  warn "no $SSH_KEY.pub — run ./bootstrap.sh 90 first, then re-run this module."
  return 0 2>/dev/null || exit 0
fi

# Load the key into an agent for this run so the clones below don't re-prompt.
ssh-add -l >/dev/null 2>&1 || eval "$(ssh-agent -s)" >/dev/null 2>&1
ssh-add "$SSH_KEY" >/dev/null 2>&1 || warn "could not add key to agent (passphrase prompt may repeat)"

# --- register the key with GitHub -------------------------------------------
# GitHub always closes the -T session with exit status 1, even on a successful
# auth. Under `set -o pipefail` (bootstrap.sh sets it) that non-zero status wins
# over grep's success and the whole pipeline reports failure — so this check used
# to return "not registered" on a box whose key GitHub accepts perfectly well,
# and every repo below was skipped. Capture first, match second.
github_ssh_ok() {
  local out
  out="$(ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes -T git@github.com 2>&1)"
  case "$out" in *'successfully authenticated'*) return 0 ;; *) return 1 ;; esac
}

GH_SSH_OK=0
if github_ssh_ok; then
  GH_SSH_OK=1
  ok "GitHub already recognises this key."
elif have gh && gh auth status >/dev/null 2>&1; then
  # Offer the automated path first — gh can upload the key for you.
  log "Adding this key to your GitHub account via gh…"
  gh ssh-key add "$SSH_KEY.pub" --title "w1ld0s-$(date +%Y%m%d)" >/dev/null 2>&1 \
    && ok "key uploaded to GitHub" || warn "gh ssh-key add failed (needs the 'admin:public_key' scope)"
  github_ssh_ok && GH_SSH_OK=1
fi

if [ "$GH_SSH_OK" -ne 1 ]; then
  hr2() { printf '\033[1;35m%s\033[0m\n' "──────────────────────────────────────────────────────────"; }
  hr2
  printf '\033[1;35m  ACTION REQUIRED — add this key to GitHub\033[0m\n'
  hr2
  printf '\n'
  cat "$SSH_KEY.pub" 2>/dev/null
  printf '\n'
  cat <<'EOF'
  1. Copy the public key printed above.
  2. Open  https://github.com/settings/ssh/new
     Title: w1ld0s      Key type: Authentication Key
  3. Paste and save.

  Or do it from the CLI instead:
       gh auth login                       # needs the admin:public_key scope
       gh ssh-key add ~/.ssh/id_ed25519.pub --title w1ld0s

  Verify, then re-run this module:
       ssh -T git@github.com               # expect "successfully authenticated"
       ./bootstrap.sh 95
EOF
  hr2
  warn "Skipping the private clones until the key is registered."
  return 0 2>/dev/null || exit 0
fi

# --- clone ------------------------------------------------------------------
for repo in "${PRIVATE_REPOS[@]}"; do
  # Destination name is the repo basename, matching clone_or_pull's default.
  dest="$REPOS_DIR/$(basename "${repo%.git}")"
  clone_or_pull "$repo" "$dest"
done

ok "private overlay: ${#PRIVATE_REPOS[@]} repo(s) processed."
